---
- name: Undeploy Mirth from the provisioned environment
  hosts: local
  connection: local
  gather_facts: false
  vars:
    state: absent
  tasks:
    - name: Import application-common role
      import_role:
        name: application-common

    - name: Destroy Mirth service
      import_role:
        name: mirth
        tasks_from: configure-mirth.yml
