- name: Run always tasks
  hosts: local
  connection: local
  tasks:
    - name: Include always role
      include_role:
        name: always
  tags: ['always']

- name: Create/Configure AWS Backup
  hosts: local
  connection: local
  vars:
    state: present
  tasks:
    - name: Include configure-aws-backup role
      include_role:
        name: configure-aws-backup
  tags: ['configure-aws-backup']
