---
- name: Unconfigure Ingress Mirth
  hosts: local
  connection: local
  gather_facts: false
  vars:
    state: absent
  tasks:
    - name: Import application-common role
      import_role:
        name: application-common

    - name: Prepare to use the bastion host
      import_role:
        name: bastion
        tasks_from: pre.yml

    - name: Prepare to connect with Ingress Mirth
      import_role:
        name: ingress-mirth
        tasks_from: pre.yml

    - name: Do local preparation for Ingress Mirth setup
      import_role:
        name: ingress-mirth
        tasks_from: locals.yml

    - name: Create temporary private key file for bastion host, ubuntu
      vars:
        aws_secret_key_name_var: "{{ aws_secret_bastion_host_ubuntu_private_key }}"
        localhost_key_path_var: "{{ bastion_host_ubuntu_private_key_path }}"
      import_role:
        name: application-secret
        tasks_from: create-temporary-key-file.yml

    - name: Create temporary private key file for ingress mirth, ubuntu
      vars:
        aws_secret_key_name_var: "{{ aws_secret_ingress_mirth_ubuntu_private_key }}"
        localhost_key_path_var: "{{ ingress_mirth_ubuntu_private_key_path }}"
      import_role:
        name: application-secret
        tasks_from: create-temporary-key-file.yml

- name: Configure Ingress Mirth
  hosts: ingress-mirth.{{ env }}.application.codametrix.com
  gather_facts: false
  vars:
    # Definitely prefer the first configuration,
    # but it doesn't seem to want to work.
    #ansible_ssh_common_args: "-C -F {{ temp_directory }}/ssh-{{ env }}-ingress.cfg"
    ansible_ssh_common_args: >
      -o ProxyCommand="ssh -i {{ bastion_host_ubuntu_private_key_path }}
      -o StrictHostKeyChecking=no
      -q
      -A ubuntu@ingress-bastion.{{ env }}.application.codametrix.com nc %h %p"
    state: absent
  tasks:
    - name: Import application-common role
      import_role:
        name: application-common

    - name: Prep Ingress Mirth
      vars:
        eth1_ip_address: "{{ partners_networking_ingress_mirth_ip }}"
        eth1_cidr_block: "{{ partners_networking_ingress_mirth_ip }}/24"
        eth2_ip_address: "{{ cumedicine_networking_ingress_mirth_ip }}"
        eth2_cidr_block: "{{ cumedicine_networking_ingress_mirth_ip }}/24"
        gateway_ip_address: "{{ ingress_ip_range_prefix }}.103.1"
        mirth_db_secret: "{{ hostvars['localhost']['mirth_db_secret'] }}"
        image_versions: "{{ hostvars['localhost']['image_versions'] }}"
      import_role:
        name: ingress-mirth
        tasks_from: configure-mirth.yml

- name: Delete temporary files
  hosts: local
  connection: local
  gather_facts: false
  vars:
    state: absent
  tasks:
    - name: Import application-common role
      import_role:
        name: application-common

    - name: Delete temporary private key file for ubuntu on the bastion host
      vars:
        localhost_temporary_key_path_var: "{{ bastion_host_ubuntu_private_key_path }}"
      import_role:
        name: application-secret
        tasks_from: delete-temporary-key-file.yml

    - name: Delete temporary private key file for ubuntu on ingress mirth
      vars:
        localhost_temporary_key_path_var: "{{ ingress_mirth_private_key_path }}"
      import_role:
        name: application-secret
        tasks_from: delete-temporary-key-file.yml
