---
- name: Terraform block
  block:
    - name: "Set keypair state to {{ state }}"
      community.general.terraform:
        force_init: "{{ force_init }}"
        project_path: "{{ keypair_terraform_path }}"
        state: "{{ state }}"
        variables_file: terraform.tfvars
      register: terraform_run
  rescue:
    - name: Terraform failed with the following error(s)
      fail:
        msg: "{{ terraform_run.msg.split('\n') }}"
