---
region: us-east-1
management_bucket: management.onboarding.codametrix.com
env: onboarding

foreign_accounts:
  - "733943117466" # cmx stage
  - "075380275136" # legacy production
  - "804152217010" # cmx ml research

# ECR repos that will be enabled for cross-account access
ecr_repos: []

# S3 Buckets that access will be given to.
s3_buckets:
  data-lake.onboarding.application.codametrix.com:
      - bucket_object_spec: "*"
        bucket_object_actions:
          - s3:Get*
          - s3:List*
        bucket_actions:
          - s3:Get*
          - s3:List*
        foreign_account:
          - 733943117466 # cmx stage
          - 804152217010 # cmx ml research

      - bucket_object_spec: "icm/*" # !!! Note: Temporary - used for production ACT Gateway integration with the data lake (for the Rad Recon report)
        bucket_object_actions:
          - s3:GetObject
          - s3:PutObject
          - s3:PutObjectAcl
        bucket_actions:
          - s3:ListBucket
        foreign_account:
          - 075380275136

kms_keys:
  - key_alias: "alias/CodaMetrixApplication-{{ env }}-application_data_lake_emr_kms_key" # Give access to the data lake bucket to the stage1 account
    key_operations:
      - Encrypt
      - Decrypt
      - DescribeKey
      - GenerateDataKey
