---
- name: Generate ~/.aws/credentials
  no_log: true
  template:
    dest: "/var/lib/awx/.aws/credentials"
    src: credentials.j2
  when: (aws_access_key is defined) and
        (aws_secret_key is defined) and
        (aws_session_token is defined)

