---
- name:  Delete a user
  hosts: local
  connection: local
  gather_facts: false
  vars_prompt:
    - name: delete_user
      prompt: Username of the user to delete
      private: no
  pre_tasks:
    - name: Re-export delete_user for cross playbook visibility
      set_fact:
        delete_user: '{{ delete_user }}'
  tasks:
    - name: Import environment-common role
      import_role:
        name: environment-common

    - name: Apply preparatory configuration for the bastion
      import_role:
        name: bastion
        tasks_from: pre.yml

    # TODO: [DEVOPS-386] shorten varibles definitions to be less than 80 char
    - name: "Create temporary private key file for
        bastion host ubuntu user with permissions"
      vars:
        aws_secret_key_name_var: "{{ aws_secret_bastion_host_ubuntu_private_key }}"
        localhost_key_path_var: "{{ bastion_host_ubuntu_private_key_path }}"
      import_role:
        name: environment-secret
        tasks_from: create-temporary-key-file.yml

- name: Delete user from bastion
  hosts: bastion
  gather_facts: false
  vars:
    ansible_ssh_args: "-C -F {{ temp_directory }}/ssh-{{ env }}.cfg"
    delete_user: "{{ hostvars['localhost']['delete_user'] }}"
  tasks:
    - name: Import environment-common role
      import_role:
        name: environment-common

    - name: Delete user from the bastion host
      import_role:
        name: bastion
        tasks_from: delete-user.yml

- name: Perform cleanup tasks
  hosts: local
  connection: local
  gather_facts: false
  vars:
    state: present
  tasks:
    - name: Import environment-common role
      import_role:
        name: environment-common

    # TODO: [DEVOPS-386] shorten varibles definitions to be less than 80 char
    - name: Delete temporary private key file for ubuntu user of bastion host
      vars:
        localhost_temporary_key_path_var: "{{ bastion_host_ubuntu_private_key_path }}"
      import_role:
        name: environment-secret
        tasks_from: delete-temporary-key-file.yml
