---
- name: Lookup public key in AWS secret manager and export it to env
  set_fact:
    "{{ aws_secret_keypair_public_key }}" : "{{ lookup('aws_secret',
       '{{ aws_secret_private_key_var }}.pub',
       region=region) }}"
