---
- name: Set New Relic Namespace resource state to {{ state }}
  community.kubernetes.k8s:
    context: "arn:aws:eks:{{ region }}:{{ aws_account_id }}:cluster/{{ cluster_name }}"
    namespace: kube-system
    resource_definition: "{{ lookup('template',
      'new-relic-namespace.yml.j2') }}"
    state: "{{ state }}"

- name: Set New Relic ExternalSecrets resource states to {{ state }}
  community.kubernetes.k8s:
    context: "arn:aws:eks:{{ region }}:{{ aws_account_id }}:cluster/{{ cluster_name }}"
    namespace: new-relic
    resource_definition: "{{ lookup('template',
      'externalsecrets.yml.j2') }}"
    state: "{{ state }}"

- name: Set kubernetes New Relic infrastructure resources state to {{ state }}
  community.kubernetes.k8s:
    context: "arn:aws:eks:{{ region }}:{{ aws_account_id }}:cluster/{{ cluster_name }}"
    namespace: new-relic
    resource_definition: "{{ lookup('template',
      'newrelic-infrastructure.yml.j2') }}"
    state: "{{ state }}"

- name: Set kubernetes New Relic metadata injection resources state to {{ state }}
  community.kubernetes.k8s:
    context: "arn:aws:eks:{{ region }}:{{ aws_account_id }}:cluster/{{ cluster_name }}"
    namespace: new-relic
    resource_definition: "{{ lookup('template',
      'newrelic-metadata-injection.yml.j2') }}"
    state: "{{ state }}"

- name: Set kubernetes New Relic kube event resources state to {{ state }}
  community.kubernetes.k8s:
    context: "arn:aws:eks:{{ region }}:{{ aws_account_id }}:cluster/{{ cluster_name }}"
    namespace: new-relic
    resource_definition: "{{ lookup('template', 'newrelic-kube-events.yml.j2') }}"
    state: "{{ state }}"

- name: Set kubernetes New Relic prometheus resources state to {{ state }}
  community.kubernetes.k8s:
    context: "arn:aws:eks:{{ region }}:{{ aws_account_id }}:cluster/{{ cluster_name }}"
    namespace: new-relic
    resource_definition: "{{ lookup('template', 'newrelic-prometheus.yml.j2') }}"
    state: "{{ state }}"

- name: Set kubernetes New Relic state metrix resources state to {{ state }}
  community.kubernetes.k8s:
    context: "arn:aws:eks:{{ region }}:{{ aws_account_id }}:cluster/{{ cluster_name }}"
    namespace: new-relic
    resource_definition: "{{ lookup('template',
      'newrelic-state-metrix.yml.j2') }}"
    state: "{{ state }}"

- name: Set kubernetes New Relic logging resources state to {{ state }}
  community.kubernetes.k8s:
    context: "arn:aws:eks:{{ region }}:{{ aws_account_id }}:cluster/{{ cluster_name }}"
    namespace: new-relic
    resource_definition: "{{ lookup('template',
      'newrelic-logging.yml.j2') }}"
    state: "{{ state }}"
