---
- name: Add Mirth instance to the in-memory inventory
  add_host:
    ansible_host: "mirth.{{ env }}.trafficcop.codametrix.com"
    ansible_ssh_private_key_file: "{{ mirth_ubuntu_private_key_path }}"
    ansible_user: "{{ mirth_login_username }}"
    group: mirth
    name: "mirth.{{ env }}.trafficcop.codametrix.com"
