---
- name: Retrieve database credentials secret
  set_fact:
    mirth_db_secret: "{{ lookup('aws_secret',
      ingress_mirth_database_secret_name,
      region=region) }}"

- name: Clone cmx-deploy-config repo
  git:
    accept_hostkey: true
    depth: 1
    dest: "{{ temp_directory }}/cmx-deploy-config"
    repo: git@github.com:CodaMetrix/cmx-deploy-config.git
    version: "{{ deploy_config_branch }}"

- name: Parse Service Version(s)
  set_fact:
    image_versions: "{{ lookup('file',
      '{{ temp_directory }}/cmx-deploy-config/service-versions-{{ env }}.yml')|from_yaml }}"

- name: Remove cmx-deploy-config repo
  file:
    path: "{{ temp_directory }}/cmx-deploy-config"
    state: absent

- name: Gather facts about ingress mirth
  community.aws.ec2_instance_info:
    filters:
      "tag:Environment": "{{ env }}"
      "tag:Type": ingress_mirth
      "instance-state-name": running
    region: "{{ region }}"
  register: ingress_mirth_instance_facts

# TODO: [DEVOPS-386] shorten varibles definitions to be less than 80 char
- name: Pull out a few key facts for use in configuring the Mirth instance
  set_fact:
    ingress_mirth_subnet_id: "{{ ingress_mirth_instance_facts.instances[0].network_interfaces[0].subnet_id }}"
    ingress_mirth_eni_id: "{{ ingress_mirth_instance_facts.instances[0].network_interfaces[0].network_interface_id }}"

- name: Assign secondary IP addresses to Mirth
  amazon.aws.ec2_eni:
    eni_id: "{{ ingress_mirth_eni_id }}"
    region: "{{ region }}"
    secondary_private_ip_addresses: "{{ secondary_private_ip_addresses }}"
    subnet_id: "{{ ingress_mirth_subnet_id }}"
  when: (enable_customer_networking)
