---
- name: Add Ingress Mirth instance to the in-memory inventory
  add_host:
    ansible_host: "ingress-mirth.{{ env }}.application.codametrix.com"
    ansible_ssh_private_key_file: "{{ ingress_mirth_ubuntu_private_key_path }}"
    ansible_user: "{{ ingress_mirth_login_username }}"
    group: ingress_mirth
    name: "ingress-mirth.{{ env }}.application.codametrix.com"
