# Peering connections for the proddr environment

application_peer_vpc_routes:
  - pcx_name: DataCentral3-CMXProdDRApplication # Data Central 3 <-> ProdDR Application
    destination_cidr: 10.73.0.0/16
  - pcx_name: CMXProdDRApp-CMXProdDRIngress # Application Mirth <-> Ingress Mirth
    destination_cidr: 10.66.0.0/16
  - pcx_name: ToolsNet-CMXProdDR # Tools Network <-> ProdDR
    destination_cidr: "{{ codametrix_tools_cidr }}"
  - pcx_name: ACTProduction-CMXProdDRApplication
    destination_cidr: 10.1.0.0/16

ingress_peer_vpc_routes:
  - pcx_name: CMXOnboardingIngress-CMXProdDRIngress # Onboarding Ingress -> ProdDR Ingress
    destination_cidr: 10.54.0.0/16
  - pcx_name: CMXProdDRApp-CMXProdDRIngress # Application Mirth <-> Ingress Mirth
    destination_cidr: 10.65.0.0/16
  - pcx_name: ToolsNet-CMXProdDRIngress # Tools Network <-> ProdDR Ingress
    destination_cidr: "{{ codametrix_tools_cidr }}"
